### ISSUE TITLE
can't compile on rust 1.76 unknown feature `generator_trait`

### ISSUE THREAD

**Issue by pymongo** [swimos/ratchet#11]
```
error[E0635]: unknown feature `generator_trait`
  --> /home/w/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratchet-1.2.0/src/lib.rs:23:25
   |
23 | #![feature(trusted_len, generator_trait, never_type,)]
```

**Comment by SirCipher** [comment]
@pymongo thank you for raising an issue and apologies for the late response. I cannot reproduce this error on 1.76.0. Are you able to provide some more details?
